// import React from 'react';
import './Privacypolicy.css'; // direct import

const Privacypolicy = () => {
  return (
    <div className="privacyPolicyContainer">
      <h1>Privacy Policy</h1>
      <p>Effective date: 2022-07-28</p>

      <h2>1. Introduction</h2>
      <p>Welcome to Houseliv.</p>
      <p>Houseliv (“us”, “we”, or “our”) operates <a href="https://www.houseliv.com/">https://www.houseliv.com/</a>(hereinafter referred to as “Service”).</p>

      <h2>2. Definitions</h2>
      <p>SERVICE means the <a href="https://www.houseliv.com/">https://www.houseliv.com/</a> website operated by Houseliv.</p>
      <p>PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
      <p>USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
      <p>COOKIES are small files stored on your device (computer or mobile device).</p>
      <p>DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
      <p>DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
      <p>DATA SUBJECT is any living individual who is the subject of Personal Data.</p>
      <p>THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>

      <h2>3. Information Collection and Use</h2>
      <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

      <h2>4. Types of Data Collected</h2>
      <p>Personal Data</p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, Country, State, Province, ZIP/Postal code, City</li>
        <li>Cookies and Usage Data</li>
      </ul>

      <h2>5. Use of Data</h2>
      <p>Houseliv uses the collected data for various purposes:</p>
      <ul>
        <li>to provide and maintain our Service;</li>
        <li>to notify you about changes to our Service;</li>
        <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
        <li>to provide customer support;</li>
        <li>to gather analysis or valuable information so that we can improve our Service;</li>
        <li>to monitor the usage of our Service;</li>
        <li>to detect, prevent and address technical issues;</li>
        <li>to fulfill any other purpose for which you provide it;</li>
        <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
        <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
        <li>to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
        <li>in any other way we may describe when you provide the information;</li>
        <li>for any other purpose with your consent.</li>
      </ul>

      <h2>6. Retention of Data</h2>
      <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.</p>

      <h2>7. Transfer of Data</h2>
      <p>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>

      <h2>8. Disclosure of Data</h2>
      <p>We may disclose personal information that we collect, or you provide:</p>
      <ul>
        <li>Disclosure for Law Enforcement.</li>
        <li>Business Transaction.</li>
        <li>Other cases.</li>
      </ul>

      <h2>9. Security of Data</h2>
      <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure.</p>

      <h2>10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
      <p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.</p>
      <ul>
        <li>The right to access, update or to delete the information we have on you;</li>
        <li>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
        <li>The right to object. You have the right to object to our processing of your Personal Data;</li>
        <li>The right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
        <li>The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
        <li>The right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
      </ul>

      <h2>11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</h2>
      <p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy.</p>
      <ul>
        <li>users can visit our site anonymously;</li>
        <li>our Privacy Policy link includes the word “Privacy”, and can easily be found on the home page of our website;</li>
        <li>users will be notified of any privacy policy changes on our Privacy Policy Page;</li>
        <li>users are able to change their personal information by emailing us at<a href="mailto:info@houseliv.com">info@houseliv.com</a> </li>
      </ul>

      <h2>12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</h2>
      <p>If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it.</p>
      <ul>
        <li>What personal information we have about you.</li>
        <li>To delete your personal information.</li>
        <li>To stop selling your personal information.</li>
      </ul>

      <h2>13. Service Providers</h2>
      <p>We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>

      <h2>14. Analytics</h2>
      <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

      <h2>15. CI/CD tools</h2>
      <p>We may use third-party Service Providers to automate the development process of our Service.</p>

      <h2>16. Behavioral Remarketing</h2>
      <p>We may use remarketing services to advertise on third party websites to you after you visited our Service.</p>

      <h2>17. Links to Other Sites</h2>
      <p>Our Service may contain links to other sites that are not operated by us.</p>

      <h2>18. Children’s Privacy</h2>
      <p>Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).</p>

      <h2>19. Changes to This Privacy Policy</h2>
      <p>We may update our Privacy Policy from time to time.</p>

      <h2>20. Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, please contact us by <a href="mailto:info@houseliv.com">info@houseliv.com</a> </p>
    </div>
  );
};

export default Privacypolicy;
